### ISSUE TITLE
Configurable max-mem in cargo.toml

### ISSUE THREAD

**Issue by nhynes** [oasislabs/mantle#59]
```toml
[metadata.oasis]
max-mem = XXX
```

contracts require more mem than is provided by wasm-build and wasm-build is no longer visible to the user
